name: rethinking
channels: 
        - r
        - conda-forge
dependencies: 
        - r-essentials
        - r-rstan
        - r-devtools
        - r-loo
        - r-coda
        - r-mvtnorm
        - r-dagitty
        - jupyterlab
        - numpyro
        - pymc3
        - arviz
        - matplotlib
        - seaborn
        - jax
        - altair
        - mkl-service
        - pip
        - pip:
                - causalgraphicalmodels
                - daft
                - watermark
